spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    gcp:
      project-id: ${GOOGLE_PROJECT_ID}
      credentials:
        location: ${GOOGLE_APPLICATION_CREDENTIALS}
server:
  servlet:
    context-path: /v1/api
  port: 8081

jwt:
  secret: nx4bak6442nojjhf83smacno9j31jcch87h=c2ee2ybc2yegce
  expiration-ms: 3600000

springdoc:
  swagger-ui:
    enabled: true

services:
  chatting:
    apikey: vV3KptV5DpX


